### PR TITLE
Allow SecurityRealm#getUserIdStrategy to be customizable

### PR DESCRIPTION
**Pull request by eva-mueller-coremedia**
Allow SecurityRealm#getUserIdStrategy to be customizable. This way, the plugin can be aligned with the ID strategy of the configured Identity Provider.

This is necessary, when the configured Identity Provider works with **case-sensitive** usernames. The Jenkins default is `case-insensitive`. The default leads to unwanted behaviour, when the configured Identity Provider has `case-sensitive` usernames, i.e., if a user with name `test-user` logs in, then a new log-in by the user `Test-User` will return the data of user `test-user`.

### Testing done

* Extend `PluginTest.java` to cover the case-sensitive and case-insensitive case.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by jtnord — CHANGES_REQUESTED** [review]
There is also the group strategy to cover.
There is code with all of this tested and ready that would conflict, so would recommend waiting for that rather than duplicating

**Comment by eva-mueller-coremedia** [comment]
Hi @jtnord - thanks for having a look at this PR.

> There is also the group strategy to cover.
There is code with all of this tested and ready that would conflict, so would recommend waiting for that rather than duplicating

Unfortunately, I do not understand your remark. Do you mean: There is a not-yet-pushed branch which will cover the customizable ID strategy?

**Comment by jtnord** [comment]
> Hi @jtnord - thanks for having a look at this PR.
> 
> > There is also the group strategy to cover.
> There is code with all of this tested and ready that would conflict, so would recommend waiting for that rather than duplicating
> 
> Unfortunately, I do not understand your remark. Do you mean: There is a not-yet-pushed branch which will cover the customizable ID strategy?

there is code that covers the id strategy changes for both users and groups that has not been pushed but will be shortly

**Comment by eva-mueller-coremedia** [comment]
> > Hi @jtnord - thanks for having a look at this PR.
> > 
> > > There is also the group strategy to cover.
> > There is code with all of this tested and ready that would conflict, so would recommend waiting for that rather than duplicating
> > 
> > Unfortunately, I do not understand your remark. Do you mean: There is a not-yet-pushed branch which will cover the customizable ID strategy?
> 
> there is code that covers the id strategy changes for both users and groups that has not been pushed but will be shortly

Ok. Good to know. Looking forward to see the feature soon.

I assume, I can close this PR, right?!

**Comment by eva-mueller-coremedia** [comment]
Already implemented but not yet pushed.

**Comment by jtnord** [comment]
@eva-mueller-coremedia do you have a Jenkins Jira ID?

**Comment by eva-mueller-coremedia** [comment]
@jtnord No, I have no Jenkins Jira ID

**Comment by jtnord** [comment]
> @jtnord No, I have no Jenkins Jira ID

would you mind signing up at https://accounts.jenkins.io/signup?

**Comment by eva-mueller-coremedia** [comment]
> > @jtnord No, I have no Jenkins Jira ID
> 
> @eva-mueller-coremedia would you mind signing up at [accounts.jenkins.io/signup](https://accounts.jenkins.io/signup)?

Done... My user name is `eva_mueller`

**Comment by eva-mueller-coremedia** [comment]
Successfully logged in...

**Comment by eva-mueller-coremedia** [comment]
@jtnord - thanks for sharing. Looking forward to see the solution in a release! Thanks a lot.

**Pull request closed without merging**
