### PR TITLE
New config option: Enable AWS Cognito Logout

### PR DESCRIPTION
**Pull request by eva-mueller-coremedia**
Unfortunately, AWS Cognito IdP’s Discovery Endpoint `https://cognito-idp.region.amazonaws.com/REGION_POOLID/.well-known/openid-configuration` does **not** return an `end_session_endpoint` URL entry, i.e. AWS Cognito does not follow the OpenID Connect RP-Initiated Logout specification.

For this case, I added a new configuration option, which addresses this fact _(that AWS Cognito does not follow the OpenID Connect RP-Initiated Logout specification)_.

See also https://github.com/jenkinsci/oic-auth-plugin/issues/229

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by michael-doubez** [comment]
PR has to be refused as it being a specific use case on a non-conformant OIDC provider.

**Comment by eva-mueller-coremedia** [comment]
@michael-doubez Since **AWS Cognito** is a [non-conformant OIDC provider concerning the logout mechanism](https://github.com/jenkinsci/oic-auth-plugin/issues/229#issuecomment-1583438330).
Also, the `well-known/openid-configuration` config does not return the property `end_session_endpoint` (same seems to hold for [Google](https://accounts.google.com/.well-known/openid-configuration)).

Before I try to provide a new PR which tries to solve the problem in a more generic way: 
Will you also refuse another PR because the main problem is that **AWS Cognito** is a non-conformant OIDC provider for the logout case and every solution will thus bypass the standard?

**Comment by michael-doubez** [comment]
@eva-mueller-coremedia hello. Coming back to this issue, why can't you use the manual config as in #95 ?

**Comment by eva-mueller-coremedia** [comment]
@michael-doubez hello. If I remember correctly, this did not work for some reason. But I will try this again. Will let you know.

**Comment by eva-mueller-coremedia** [comment]
@michael-doubez I tested it as suggested and it works now. 👍 

I also discovered that meanwhile AWS **does return** the property `end_session_endpoint` via the `well-known/openid-configuration` config.

Only the **Post logout redirect URL** does not work as I expect it. No redirect happens. But maybe I don't understood its purpose correctly.
I assumed, if I specify `https://my-url`, after logout, I will get redirected to this page.

**Comment by michael-doubez** [comment]
Well, the client id seems to be required: https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html#get-logout

**Comment by eva-mueller-coremedia** [comment]
Do I understand you correctly that you assume that the **Post logout redirect URL** also required the Client ID?
Here my config which works regarding the logout but not the redirect

Screenshot 2024-05-24 at 08 02 25

**Comment by michael-doubez** [comment]
Don t fill the Post Logout URI parameter since you already handle it yourself in the End Session URL.

I would suggest you put the client id as first parameter (should not be needed but I don t know aws provider - some do care).

And URL encode the content of 'logout_url'.

**Comment by eva-mueller-coremedia** [comment]
Here my results - All entries were made in **End session URL for OpenID Provider** and no **Post logout redirect URL** has been set.

⚠️ It seems to be important that it ends with a `&`

👎  Result in **Cognito Logout error** `Required String parameter 'redirect_uri' is not present`

* `https://<URL>/logout?client_id=<ID>&logout_uri=https://jenkins.docker.localhost/OicLogout`

-----

😞  Redirects to `https://jenkins.docker.localhost/OicLogout/`

* `https://<URL>/logout?logout_uri=https://jenkins.docker.localhost/OicLogout&client_id=<ID>&`
* `https://<URL>/logout?logout_uri=https%3A%2F%2Fjenkins.docker.localhost%2FOicLogout&client_id=<ID>&`
* `https://<URL>/logout?client_id=<ID>&logout_uri=https://jenkins.docker.localhost/OicLogout&`

-----

👎  Results in **Invalid client id.** & No Logout done

* `https://<URL>/logout?logout_uri=https://jenkins.docker.localhost/OicLogout&client_id=<ID>`
* `https://<URL>/logout?logout_uri=https%3A%2F%2Fjenkins.docker.localhost%2FOicLogout&client_id=<ID>`

**Comment by eva-mueller-coremedia** [comment]
@michael-doubez Do my result help?

**Comment by michael-doubez** [comment]
@eva-mueller-coremedia Hello. Definitely. Thank you. I've have not had the opportunity to check the consistency with the code.

I'll see how it works with Cognito's API.

**Pull request closed without merging**
